<?php
/**
 * @file
 * Defines a Cancel button on node forms
 */
function druedu_cancel_form_node_form_alter(&$form, &$form_state) {
  $form['actions']['cancel'] = array(
    '#type' => 'submit',
		'#value' => t('Cancel'),
		'#weight' => 20,
    '#executes_submit_callback' => TRUE,
    '#limit_validation_errors' => array(),
    '#submit' => array('druedu_cancel_buttons_callback')
  );
}
/**
 * Custom cancel button callback.
 */
function druedu_cancel_buttons_callback($form, &$form_state) {
  $node = $form['#node'];
  druedu_redirect_callback($node, $flag = TRUE);
}